## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('example_01',
                                 ['core', 'ns3dtn_bit'])
    obj.source = 'example_01.cpp'
